### ISSUE TITLE
Error installing AmazonFling

### ISSUE THREAD

**Issue by phuockal** [crelies/FireTVKit#1]
Hello,
I got error while doing command "pod install"
"
Installing AmazonFling (1.3.5)

[!] Error installing AmazonFling
[!] /usr/bin/git clone git@gitlab.com:crelies/AmazonFling.git /var/folders/6z/w7gcrmmx50z03m9dbt_l52kr0000gn/T/d20190615-497-8gymh9 --template= --single-branch --depth 1 --branch 1.3.5

Cloning into '/var/folders/6z/w7gcrmmx50z03m9dbt_l52kr0000gn/T/d20190615-497-8gymh9'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
"

**Comment by chris-swift-dev** [comment]
Hey @phuockal ,

this shouldn't happen. I set the visibility and accessibility of the project to public. See the screenshot below.

<img width="853" alt="Screenshot 2019-06-16 at 10 12 36" src="https://user-images.githubusercontent.com/11267350/59561310-4656f280-901f-11e9-8135-c61df1e8c6a8.png">

**Comment by Phaptlq** [comment]
Hi @crelies,

i have same problem when pod install. Can you check git ?

[!] Error installing AmazonFling
[!] /usr/bin/git clone git@gitlab.com:crelies/AmazonFling.git /var/folders/tg/hv04xchd0t3_8y6ysdsklzv80000gn/T/d20190710-6614-xilwne --template= --single-branch --depth 1 --branch 1.3.5

Cloning into '/var/folders/tg/hv04xchd0t3_8y6ysdsklzv80000gn/T/d20190710-6614-xilwne'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by chris-swift-dev** [comment]
Hey ho,

as you might already know the issue was related to **git lfs**. You have to install and use _git lfs_ because of the size of the binary!
